import type { Agent, Process, Task, Credential, AuditLog } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'reasoning',
    name: 'Reasoning Agent',
    description: 'Orchestrates planning using Groq AI — runs every 30 minutes',
    status: 'running',
    lastRun: '2 minutes ago',
    nextRun: 'in 28 minutes',
    interval: '30m',
    tasksProcessed: 142,
    errorsToday: 0,
    uptime: '18h 32m',
    credentials: ['GROQ_API_KEY'],
  },
  {
    id: 'execution',
    name: 'Execution Agent (Ralph Wiggum)',
    description: 'Autonomously executes approved plans — runs every 5 minutes',
    status: 'running',
    lastRun: '1 minute ago',
    nextRun: 'in 4 minutes',
    interval: '5m',
    tasksProcessed: 89,
    errorsToday: 1,
    uptime: '18h 32m',
    credentials: ['GROQ_API_KEY'],
  },
  {
    id: 'cloud',
    name: 'Cloud Agent',
    description: 'Always-on Azure VM agent — drafts content, never executes',
    status: 'running',
    lastRun: 'just now',
    interval: 'continuous',
    tasksProcessed: 23,
    errorsToday: 0,
    uptime: '5d 12h',
    credentials: ['GROQ_API_KEY'],
  },
  {
    id: 'local-approval',
    name: 'Local Approval Agent',
    description: 'Reviews cloud drafts and executes approved actions',
    status: 'idle',
    lastRun: '45 minutes ago',
    tasksProcessed: 12,
    errorsToday: 0,
    credentials: ['EMAIL_SENDER', 'EMAIL_PASSWORD', 'GMAIL_CLIENT_ID'],
  },
  {
    id: 'gmail',
    name: 'Gmail Watcher',
    description: 'Polls Gmail API every 2 minutes for important emails',
    status: 'running',
    lastRun: '90 seconds ago',
    interval: '2m',
    tasksProcessed: 31,
    errorsToday: 0,
    uptime: '18h 32m',
    credentials: ['GMAIL_CLIENT_ID', 'GMAIL_CLIENT_SECRET'],
  },
  {
    id: 'business-audit',
    name: 'Business Audit Watcher',
    description: 'Generates weekly CEO briefing every Sunday 11 PM',
    status: 'idle',
    nextRun: 'Sunday 11 PM',
    interval: 'weekly',
    tasksProcessed: 4,
    errorsToday: 0,
    credentials: ['GROQ_API_KEY', 'SLACK_BOT_TOKEN'],
  },
];

export const mockProcesses: Process[] = [
  { id: '1', name: 'groq-reasoning-loop', status: 'online', pid: 12345, cpu: 0.4, memory: 48, uptime: '18h 32m', restarts: 0 },
  { id: '2', name: 'ralph-wiggum-loop', status: 'online', pid: 12346, cpu: 1.2, memory: 62, uptime: '18h 32m', restarts: 1, lastRestart: '6h ago' },
  { id: '3', name: 'cloud-orchestrator', status: 'online', pid: 12347, cpu: 0.1, memory: 44, uptime: '5d 12h', restarts: 0 },
  { id: '4', name: 'gmail-watcher', status: 'online', pid: 12348, cpu: 0.2, memory: 38, uptime: '18h 32m', restarts: 0 },
  { id: '5', name: 'email-mcp', status: 'online', pid: 12355, cpu: 0.1, memory: 32, uptime: '18h 32m', restarts: 0 },
  { id: '7', name: 'odoo-mcp', status: 'online', pid: 12356, cpu: 0.2, memory: 54, uptime: '18h 32m', restarts: 0 },
  { id: '8', name: 'filesystem-watcher', status: 'online', pid: 12357, cpu: 0.1, memory: 36, uptime: '18h 32m', restarts: 0 },
  { id: '9', name: 'business-audit-watcher', status: 'stopped', pid: undefined, cpu: 0, memory: 0, restarts: 0 },
  { id: '10', name: 'watchdog', status: 'online', pid: 12360, cpu: 0.1, memory: 28, uptime: '18h 32m', restarts: 0 },
];

export const mockTasks: Task[] = [
  { id: '1', title: 'Reply to client email about project timeline', type: 'email', platform: 'gmail', status: 'pending', priority: 'high', createdAt: '2 hours ago', description: 'Client asking for updated timeline on Q2 delivery' },
  { id: '2', title: 'Generate invoice for Acme Corp - $5,000', type: 'accounting', platform: 'odoo', status: 'pending', priority: 'critical', createdAt: '1 hour ago' },
  { id: '3', title: 'Follow up on overdue invoice — Beta LLC', type: 'email', platform: 'gmail', status: 'in_progress', priority: 'high', createdAt: '30 minutes ago' },
  { id: '4', title: 'Draft reply to urgent support email', type: 'email', platform: 'gmail', status: 'approved', priority: 'high', createdAt: '3 hours ago', content: 'Draft reply ready for review...' },
  { id: '5', title: 'Expense report: Cloud services March', type: 'accounting', platform: 'odoo', status: 'done', priority: 'medium', createdAt: '2 days ago' },
  { id: '6', title: 'Send monthly invoice reminder to overdue clients', type: 'email', platform: 'gmail', status: 'done', priority: 'medium', createdAt: 'yesterday' },
];

export const mockCredentials: Credential[] = [
  { id: '1', service: 'Groq AI', category: 'ai', keyName: 'GROQ_API_KEY', value: '', isSet: true, lastUpdated: '2 days ago', description: 'FREE LLM API — Primary AI engine for all agents' },
  { id: '2', service: 'Anthropic Claude', category: 'ai', keyName: 'ANTHROPIC_API_KEY', value: '', isSet: false, description: 'Optional — Claude API fallback' },
  { id: '3', service: 'OpenAI GPT', category: 'ai', keyName: 'OPENAI_API_KEY', value: '', isSet: false, description: 'Optional — GPT-4 fallback' },
  { id: '4', service: 'Ollama (Local LLM)', category: 'ai', keyName: 'OLLAMA_HOST', value: 'http://localhost:11434', isSet: true, description: 'Local LLM endpoint — optional' },
  { id: '5', service: 'Gmail OAuth', category: 'email', keyName: 'GMAIL_CLIENT_ID', value: '', isSet: true, lastUpdated: '5 days ago', description: 'Gmail API OAuth Client ID' },
  { id: '6', service: 'Gmail OAuth', category: 'email', keyName: 'GMAIL_CLIENT_SECRET', value: '', isSet: true, lastUpdated: '5 days ago', description: 'Gmail API OAuth Client Secret' },
  { id: '7', service: 'Email SMTP', category: 'email', keyName: 'EMAIL_SENDER', value: 'samiullahmalik7474@gmail.com', isSet: true, description: 'Sender email address' },
  { id: '8', service: 'Email SMTP', category: 'email', keyName: 'EMAIL_PASSWORD', value: '', isSet: true, lastUpdated: '5 days ago', description: 'Gmail app password for SMTP' },
  { id: '10', service: 'Odoo', category: 'accounting', keyName: 'ODOO_URL', value: 'http://localhost:8069', isSet: true, description: 'Odoo server URL' },
  { id: '11', service: 'Odoo', category: 'accounting', keyName: 'ODOO_DB', value: 'FTE', isSet: true, description: 'Odoo database name' },
  { id: '12', service: 'Odoo', category: 'accounting', keyName: 'ODOO_USER', value: 'admin', isSet: true, description: 'Odoo admin username' },
  { id: '13', service: 'Odoo', category: 'accounting', keyName: 'ODOO_PASSWORD', value: '', isSet: true, description: 'Odoo admin password' },
  { id: '14', service: 'Slack', category: 'notifications', keyName: 'SLACK_BOT_TOKEN', value: '', isSet: true, lastUpdated: '1 week ago', description: 'Slack bot token (xoxb-...)' },
  { id: '15', service: 'Slack', category: 'notifications', keyName: 'SLACK_APP_TOKEN', value: '', isSet: true, description: 'Slack app token (xapp-...)' },
  { id: '16', service: 'Slack', category: 'notifications', keyName: 'SLACK_DEFAULT_CHANNEL', value: '', isSet: true, description: 'Default Slack channel ID' },
];

export const mockAuditLogs: AuditLog[] = [
  { id: '1', timestamp: '2026-05-01T10:45:23Z', event_type: 'email.sent', component: 'LocalApprovalAgent', message: 'Reply sent to client@acmecorp.com — project timeline', success: true },
  { id: '2', timestamp: '2026-05-01T10:43:11Z', event_type: 'plan.generated', component: 'ReasoningAgent', message: 'Generated Plan_20260501_104311.md with 3 tasks', success: true },
  { id: '3', timestamp: '2026-05-01T10:42:05Z', event_type: 'email.received', component: 'GmailWatcher', message: 'New email from client@acmecorp.com — Priority: HIGH', success: true },
  { id: '4', timestamp: '2026-05-01T10:38:44Z', event_type: 'task.failed', component: 'GmailWatcher', message: 'Gmail API rate limit hit — retrying in 30s', success: false },
  { id: '5', timestamp: '2026-05-01T10:35:00Z', event_type: 'agent.retry', component: 'ExecutionAgent', message: 'Retrying failed task after 4s backoff (attempt 2/3)', success: true },
  { id: '6', timestamp: '2026-05-01T10:30:15Z', event_type: 'invoice.created', component: 'OdooConnector', message: 'Invoice INV/2026/001 created — Acme Corp $5,000', success: true },
  { id: '7', timestamp: '2026-05-01T10:28:33Z', event_type: 'task.approved', component: 'LocalApprovalAgent', message: 'Email draft approved and sent to client', success: true },
  { id: '8', timestamp: '2026-05-01T10:25:00Z', event_type: 'audit.query', component: 'AuditLogger', message: 'Daily audit report generated — 47 events', success: true },
];
